package com.po;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.uid
     *
     * @mbg.generated Thu Oct 10 15:01:39 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.uname
     *
     * @mbg.generated Thu Oct 10 15:01:39 CST 2019
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.usex
     *
     * @mbg.generated Thu Oct 10 15:01:39 CST 2019
     */
    private String usex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.uid
     *
     * @return the value of t_user.uid
     *
     * @mbg.generated Thu Oct 10 15:01:39 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.uid
     *
     * @param uid the value for t_user.uid
     *
     * @mbg.generated Thu Oct 10 15:01:39 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.uname
     *
     * @return the value of t_user.uname
     *
     * @mbg.generated Thu Oct 10 15:01:39 CST 2019
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.uname
     *
     * @param uname the value for t_user.uname
     *
     * @mbg.generated Thu Oct 10 15:01:39 CST 2019
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.usex
     *
     * @return the value of t_user.usex
     *
     * @mbg.generated Thu Oct 10 15:01:39 CST 2019
     */
    public String getUsex() {
        return usex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.usex
     *
     * @param usex the value for t_user.usex
     *
     * @mbg.generated Thu Oct 10 15:01:39 CST 2019
     */
    public void setUsex(String usex) {
        this.usex = usex == null ? null : usex.trim();
    }
}